### ISSUE TITLE
Strong mode

### ISSUE THREAD

**Issue by jorgjanke** [lejard-h/lawndart#28]
Any plans to implement Strong mode?
idb is a bit too tricky (for me) based on the dart.dom.indexed_db :-/
Maybe the better question is there any option that there will be a provide strong mode for dart.dom.indexed_db.

**Comment by sethladd** [comment]
No plans, unfortunately, since I'm not using this library. I'd happily accept a patch, though.

Also happy to find a new owner for this package :)

**Comment by lejard-h** [comment]
fix https://github.com/sethladd/lawndart/pull/29
